// This file is automatically generated.
// Please do not change this file!
export const currentColor: string;
export const formAccent: string;
export const formAccentDisabled: string;
export const critical: string;
export const positive: string;
export const secondary: string;
export const white: string;
