// This file is automatically generated.
// Please do not change this file!
export const xsmallText: string;
export const xsmallTextInline: string;
export const smallText: string;
export const smallTextInline: string;
export const standardText: string;
export const standardTextInline: string;
export const largeText: string;
export const largeTextInline: string;
export const level1Text: string;
export const level1TextInline: string;
export const level2Text: string;
export const level2TextInline: string;
export const level3Text: string;
export const level3TextInline: string;
