// This file is automatically generated.
// Please do not change this file!
export const activeOverlay: string;
export const content: string;
export const focusOverlay: string;
export const hoverOverlay: string;
export const root: string;
export const weak: string;
