ignores:
  - '@testing-library/dom'
  - assert
  - tsdown
  # internal
  - braid-storybook
  - braid-src
  - site
  # Used for generate-component-docs bin
  - tsx
  # Used for testing
  - \@storybook/addon-webpack5-compiler-babel
  - vitest
  - \@vitejs/plugin-react
  - \@vanilla-extract/vite-plugin
