ignores:
  - '@testing-library/dom'
  - '@types/jest'
  - assert
  - yoga-layout-prebuilt
  # internal
  - braid-src
  - site
parsers:
  '**/*.{js,cjs,ts,cts}': ['typescript']
  '**/*.tsx': ['typescript', 'jsx']
