ignores:
  - '@crackle/cli'
  - '@testing-library/dom'
  - assert
  # internal
  - braid-src
  - site
  # Used for generate-component-docs bin
  - tsx
  # Used for testing
  - vitest
  - \@vitejs/plugin-react
  - \@vanilla-extract/vite-plugin
