version: 3

groups:
  code:
    reviews:
      required: 1
    reviewers:
      teams:
        - front-end-contributors
    conditions:
      - "contains_regex(title, '^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\\(\\w+\\))?\\:\\s[A-Z].*$')"
      
