allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: false
  core-js-pure: false
  esbuild: true
  nx: false
  sku: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - sku

packages:
  - packages/*
  - integration
  - storybook
  - site

linkWorkspacePackages: 'deep'
preferWorkspacePackages: true

overrides:
  sku: 15.15.3-wip-esm-jiti-20260521063823
