// This file is automatically generated.
// Please do not change this file!
export const actionsContainer: string;
export const container: string;
export const content: string;
export const linkButton: string;
export const source: string;
export const sourceLink: string;
export const subtitle: string;
