// This file is automatically generated.
// Please do not change this file!
export const field: string;
export const fieldContainer: string;
export const focusOverlay: string;
export const hoverOverlay: string;
