// This file is automatically generated.
// Please do not change this file!
export const none: string;
export const gutter: string;
export const xxsmall: string;
export const xsmall: string;
export const small: string;
export const medium: string;
export const large: string;
export const xlarge: string;
export const xxlarge: string;
