// This file is automatically generated.
// Please do not change this file!
export const standard: string;
export const centered: string;
export const interaction: string;
export const large: string;
