// This file is automatically generated.
// Please do not change this file!
export const card: string;
export const critical: string;
export const formAccent: string;
export const formAccentDisabled: string;
export const info: string;
export const input: string;
export const inputDisabled: string;
export const selection: string;
