// This file is automatically generated.
// Please do not change this file!
export const largeText: string;
export const largeTextInline: string;
export const standardText: string;
export const standardTextInline: string;
