// This file is automatically generated.
// Please do not change this file!
export const largeText: string;
export const level1Heading: string;
export const level2Heading: string;
export const level3Heading: string;
export const standardText: string;
