// This file is automatically generated.
// Please do not change this file!
export const checkbox: string;
export const checkboxChecked: string;
export const checkboxContainer: string;
export const checkboxCritical: string;
export const checkboxDisabled: string;
export const checkboxFocus: string;
export const checkboxHover: string;
export const checkboxIcon: string;
export const children: string;
export const content: string;
export const label: string;
export const realCheckbox: string;
