// This file is automatically generated.
// Please do not change this file!
export const focusOverlay: string;
export const overlayContainer: string;
export const root: string;
export const root_isButton: string;
