// This file is automatically generated.
// Please do not change this file!
export const none: string;
export const gutter: string;
export const smallest: string;
export const smaller: string;
export const small: string;
export const medium: string;
export const large: string;
export const larger: string;
export const largest: string;
