// This file is automatically generated.
// Please do not change this file!
export const xsmall: string;
export const small: string;
export const standard: string;
export const interaction: string;
export const large: string;
export const level1: string;
export const level2: string;
export const level3: string;
