declare const sizes: {
    readonly standard: "standard";
    readonly small: "small";
};
export declare type Size = keyof typeof sizes;
export declare const root: string;
export declare const realField: string;
export declare const realFieldPosition: Record<"small" | "standard", string>;
export declare const label: Record<"small" | "standard", string>;
export declare const fieldSize: Record<"small" | "standard", string>;
export declare const slideContainerBase: string;
export declare const slideContainerSize: Record<"small" | "standard", string>;
export declare const slideTrack: Record<"small" | "standard", string>;
export declare const slideTrackBackground: string;
export declare const slideTrackSelected: string;
export declare const slider: Record<"small" | "standard", string>;
export declare const icon: string;
export declare const focusOverlay: string;
export declare const hoverOverlay: string;
export {};
