// This file is automatically generated.
// Please do not change this file!
export const realRadio: string;
export const label: string;
export const content: string;
export const radioContainer: string;
export const radio: string;
export const radioHover: string;
export const radioFocus: string;
export const radioDisabled: string;
export const radioCritical: string;
export const radioIcon: string;
export const children: string;
