// This file is automatically generated.
// Please do not change this file!
export const bar: string;
export const bar1: string;
export const bar2: string;
export const bar3: string;
export const root: string;
export const root_isHidden: string;
export const root_isOpen: string;
