// This file is automatically generated.
// Please do not change this file!
export const inline: string;
export const left: string;
export const right: string;
export const root: string;
export const up: string;
