// This file is automatically generated.
// Please do not change this file!
export const enter: string;
export const enterActive: string;
export const exit: string;
export const exitActive: string;
export const transitionContainer: string;
