// This file is automatically generated.
// Please do not change this file!
export const container: string;
export const content: string;
export const header: string;
export const menu: string;
export const menuButton: string;
export const menuButton__bar: string;
export const menuButton__bar1: string;
export const menuButton__bar2: string;
export const menuButton__bar3: string;
export const menuButton__isHidden: string;
export const menuButton__isOpen: string;
export const menu__isOpen: string;
