export declare const theme: {
    name: string;
    displayName: string;
    background: string;
    webFonts: {
        linkTag: string;
    }[];
    space: {
        grid: number;
        space: {
            gutter: number;
            xxsmall: number;
            xsmall: number;
            small: number;
            medium: number;
            large: number;
            xlarge: number;
            xxlarge: number;
        };
    };
    color: {
        background: {
            formAccentActive: string;
            formAccentHover: string;
            brandAccentActive: string;
            brandAccentHover: string;
            criticalActive: string;
            criticalHover: string;
            infoLight: string;
            promoteLight: string;
            criticalLight: string;
            positiveLight: string;
            cautionLight: string;
            neutralLight: string;
            body: string;
            brand: string;
            input: string;
            inputDisabled: string;
            brandAccent: string;
            formAccent: string;
            formAccentDisabled: string;
            selection: string;
            info: string;
            promote: string;
            card: string;
            critical: string;
            caution: string;
            positive: string;
            neutral: string;
        };
        foreground: {
            link: string;
            linkHover: string;
            linkVisited: string;
            neutral: string;
            neutralInverted: string;
            formAccent: string;
            brandAccent: string;
            critical: string;
            info: string;
            promote: string;
            positive: string;
            caution: string;
            secondary: string;
            secondaryInverted: string;
            rating: string;
        };
    };
    backgroundLightness: {
        formAccentActive: "dark" | "light";
        formAccentHover: "dark" | "light";
        brandAccentActive: "dark" | "light";
        brandAccentHover: "dark" | "light";
        criticalActive: "dark" | "light";
        criticalHover: "dark" | "light";
        infoLight: "dark" | "light";
        promoteLight: "dark" | "light";
        criticalLight: "dark" | "light";
        positiveLight: "dark" | "light";
        cautionLight: "dark" | "light";
        neutralLight: "dark" | "light";
        body: "dark" | "light";
        brand: "dark" | "light";
        input: "dark" | "light";
        inputDisabled: "dark" | "light";
        brandAccent: "dark" | "light";
        formAccent: "dark" | "light";
        formAccentDisabled: "dark" | "light";
        selection: "dark" | "light";
        info: "dark" | "light";
        promote: "dark" | "light";
        card: "dark" | "light";
        critical: "dark" | "light";
        caution: "dark" | "light";
        positive: "dark" | "light";
        neutral: "dark" | "light";
    };
    treatTheme: string;
};
