// This file is automatically generated.
// Please do not change this file!
export const container: string;
export const content: string;
export const content__isHidden: string;
export const header: string;
export const menu: string;
export const menu__isOpen: string;
