// This file is automatically generated.
// Please do not change this file!
export const block: string;
export const flex: string;
export const inline: string;
export const inlineBlock: string;
export const none: string;
