name: Preview

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Deploy preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to surge
        run: yarn deploy-preview -d braid-design-system--${GITHUB_SHA}.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
