name: Snapshot

on: push

jobs:
  annotate:
    name: Publish snapshot version
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1

      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          token: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: 'Version'
        run: pnpm exec changeset version --snapshot ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}

      - name: Create an .npmrc
        env:
          NPM_TOKEN: ${{ secrets.SEEK_OSS_CI_NPM_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: 'Publish'
        run: |
          OUTPUT=${{ github.run_number }}-output
          pnpm run publish-package -- --no-git-tags --snapshot --tag ${{ github.ref_name }} | tee $OUTPUT
          SNAPSHOT_VERSION=$(grep -E -o 'New tag:\s+(.*)' $OUTPUT | sed -r 's/New tag:  (v)?//')
          cat << EOF >> $GITHUB_STEP_SUMMARY
          ## :butterfly: New snapshot published!
          Version: \`$SNAPSHOT_VERSION\`
          \`\`\`
          yarn add braid-design-system@${{ github.ref_name }}
          \`\`\`
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}
