name: Snapshot

on: push

jobs:
  annotate:
    name: Test annotation
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: 'Test annotate'
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
