name: Snapshot

on: workflow_dispatch

jobs:
  annotate:
    name: Test annotation
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: 'Test annotate'
        run: 'echo ::notice ::This annotation should appear on the job'
